path:
  orca_path: "/home/mihail/orca303/orca"
  work_path: "/home/mihail/orca_tasks/test"

email:
  mail_successed: true #sending an email after each interim calculation
  addressees:
    - "mihail_was96@mail.ru"


